version: '3.8'

networks:
 monitoring:
   driver: bridge

volumes:
 prometheus_data: {}

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
     - prometheus_data:/prometheus
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
     - '--storage.tsdb.path=/prometheus'
     - '--web.console.libraries=/etc/prometheus/console_libraries'
     - '--web.console.templates=/etc/prometheus/consoles'
     - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - "9091:9091"

  loki:
    image: grafana/loki:2.7.2
    restart: unless-stopped
    ports:
      - "3100:3100"
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  promtail:
    image: grafana/promtail:2.7.2
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
      - ./promtail.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
     - /proc:/host/proc:ro
     - /sys:/host/sys:ro
     - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
     - 9100

  api-gateway:
    build: .
    hostname: api-gateway
    container_name: app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - loki_url=${loki_url:-http://loki:3100/api/prom/push}
      - job=${job:-api-gateway}
    env_file:
      - ./services/api-gateway/.env